### ISSUE TITLE
Add a support for Gemini 1.5 Pro

### ISSUE THREAD

**Issue by mertushka** [jehna/humanify#11]
How about adding support for Google's Gemini 1.5 Pro Model which offers 1,048,576 tokens for free?

https://aistudio.google.com/

**Comment by 0xdevalias** [comment]
AIStudio isn't accessible via API as far as I know; and they've only recently started giving API access to a limited set of people applying; limited to a single Google Cloud project ID.

So not really widely available to be integrated at this stage afaik.

**Comment by mertushka** [comment]
Any heads up? @0xdevalias @jehna

**Comment by 0xdevalias** [comment]
These days I would probably suggest widening the scope of this issue to include multiple Gemini based models, as there are things like Gemini 1.5 Flash and similar now too:

- https://ai.google.dev/pricing
- https://ai.google.dev/gemini-api/docs
- https://ai.google.dev/gemini-api/docs/quickstart?lang=node
- https://ai.google.dev/gemini-api/docs/downloads
  - > `npm install @google/generative-ai`
- https://ai.google.dev/gemini-api/docs/models/gemini
  - 1.5 Flash, 1.5 Pro, 1.0 Pro, etc
- https://ai.google.dev/gemini-api/docs/models/experimental-models

---

If this were a python based project, I would suggest that there might be benefit in implementing an abstraction library such as `litellm` (which is what `aider` uses) to ease integrating multiple new API's/model providers, but not sure if there is a well maintained equivalent for JS/TS:

- https://aider.chat/docs/llms.html
- https://github.com/BerriAI/litellm
  - > Python SDK, Proxy Server to call 100+ LLM APIs using the OpenAI format - [Bedrock, Azure, OpenAI, VertexAI, Cohere, Anthropic, Sagemaker, HuggingFace, Replicate, Groq]
- https://docs.litellm.ai/
  - https://docs.litellm.ai/#quick-start-proxy---cli
    - It seems it can be run as a standalone proxy; but that would then be introducing reliance on python again like the old version of this project had.
  - https://docs.litellm.ai/docs/providers
- https://www.reddit.com/r/node/comments/16wialr/similar_library_to_litellm_a_python_library/
  - https://github.com/token-js/token.js
    - > Token.js
      > Integrate 200+ LLMs with one TypeScript SDK using OpenAI's format. Free and open source. No proxy server required.
    - https://docs.tokenjs.ai/
