### ISSUE TITLE
Replace ts-node with tsx

### ISSUE THREAD

**Issue by AidanWelch** [jehna/humanify#13]
`ts-node` is frustratingly broken for many people in many projects.  `tsx ` [doesn't have that problem](https://stackoverflow.com/questions/63742790/unable-to-import-esm-ts-module-in-node/74608156#74608156) to my knowledge.

**Comment by jehna** [comment]
Yes, let's do this! I've migrated to `tsx` in all of my new projects aready.

**Comment by AidanWelch** [comment]
@jehna should I open a PR or will you do it?
