### ISSUE TITLE
Broken Dependencies on environment.yaml

### ISSUE THREAD

**Issue by fear-rush** [jehna/humanify#15]
Lot of issues when installing environment such as:
- Missing zmq module
- Missing outline module
- Python 3.9 doesn't support match-case statement

**Comment by jehna** [comment]
Oh, it seems that python dependencies file is missing, whoopsie. I'll check if I have a working env that I can freeze

**Comment by jehna** [comment]
@fear-rush should be fixed now, updated conda dependencies to match a working environment

**Comment by jehna** [comment]
You might need to recreate the conda environment by following the readme instructions or apply:
```bash
conda activate $YOURENV && conda env update --file environment.yml
```
