### ISSUE TITLE
High memory usage when using local inference with llama2-7b model

### ISSUE THREAD

**Issue by fear-rush** [jehna/humanify#16]
Is there any workarounds that i can do to reduce the memory usage? For the context i'm using Macbook M1 Pro with 16GB memory and the memory usage when running local inference is too high. It uses around 34GB of memory. I tried to Convert model parameters to half-precision (float16) to reduce memory usage but still doesnt work.

**Comment by jehna** [comment]
@fear-rush The new v2 now has a much smaller default model that should run on 8gb RAM.
