### ISSUE TITLE
Expected ',' or '}' after property value in JSON at position 2262

### ISSUE THREAD

**Issue by igorleonir** [jehna/humanify#17]
I tried to run humanify on a big script (6059 lines) and it returns this error: 
<img width="852" alt="image" src="https://github.com/jehna/humanify/assets/97915639/31115c60-53b6-4649-938f-fe9b4cef8c7b">
This script is validated. I tested with another scripts and worked fine.

**Comment by 0xdevalias** [comment]
Potentially related:

- https://github.com/jehna/humanify/issues/12

**Comment by 0xdevalias** [comment]
> This should now be fixed in v2 since there's the long awaited JSON mode with the new [structured outputs](https://openai.com/index/introducing-structured-outputs-in-the-api/).  Please take a look and repoen if anything comes up
> 
> _Originally posted by @jehna in https://github.com/jehna/humanify/issues/22#issuecomment-2282876269_
