### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Zeng-aN** [jehna/humanify#207]
Hello there, I've encountered an installation issue, and the error message is as follows:
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.

changed 280 packages in 53s

58 packages are looking for funding
 
![image](https://github.com/user-attachments/assets/4fbcb2a2-e778-4a2b-8b91-eb2e28a84006)
The error message for the local model download is as follows:

(node:5657) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Model "2b" already 
![image](https://github.com/user-attachments/assets/cc81ba7d-3d8a-40d2-b3a1-fb0302951624)
The error message for executing the command `humanify local /Users/kali/Downloads/1.js` is as follows:
![image](https://github.com/user-attachments/assets/f65d3bbd-0a8c-4dd7-b832-8b0ba2cc7375)

node == v22.11.0

**Comment by jehna** [comment]
Hey! These seem to be warning level messages from third party dependencies, which should not affect humanify's workings. What happens after the last `processing file 1/1` message?

**Comment by Zeng-aN** [comment]
He has always been at 0%.

**Comment by jehna** [comment]
What's your gpu? To me it seems that it just takes a lot of time to process if there's no other errors.

Have you tried `--disableGpu`?

**Comment by Zeng-aN** [comment]
Thank you for your reply, my GPU is AMD Radeon Pro 5300M.
I will try the suggestions you've given.

**Comment by Zeng-aN** [comment]
There has been progress, thank you for your solution, but the progress bar is still too slow

**Comment by jehna** [comment]
> AMD Radeon Pro 5300M
If I googled correctly, there's 4gb of memory, which is probably too low for the model. I think you'd need much beefier gpu to run Humanify locally

**Comment by Zeng-aN** [comment]
Yes, I'm also aware of this issue, and it took me 3 hours to complete only 10%. It's time to upgrade my equipment. Also, thank you for taking the time to answer my question.
