### ISSUE TITLE
Coalescence

### ISSUE THREAD

**Issue by neoOpus** [jehna/humanify#226]
I've found this and thought that it is maybe interesting for this project.

https://blog.dottxt.co/coalescence.html#org25a7abb

**Comment by jehna** [comment]
Interesting! Unfortunately there's not much humanify can do, as it's using llama.cpp for inference under the hood. This would need to be implemented in llama.cpp side, but unfortunately there seems not to be that much interest:

https://github.com/ggerganov/llama.cpp/issues/5292

**Comment by neoOpus** [comment]
I see thank you for the explanation.

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/ggml-org/llama.cpp/discussions/5455
  - > It's not implemented - the main problem is that a deterministic string can be represented in many different ways in terms of tokens (e.g. "hello" -> ["h", "ello"], ["he", "llo"], ["hel", "l", "o"], ...) so it is not clear beforehand which representation the LLM would generate.
    > 
    > The closest thing to this functionality that can be done even now is to use a fast draft model which you also constrain with the same grammar (see `speculative` example)
    > 
    > _Originally posted by @ggerganov in https://github.com/ggml-org/llama.cpp/discussions/5455#discussioncomment-8438137_
- https://github.com/dottxt-ai/outlines
  - > Structured Text Generation
- https://github.com/dottxt-ai/outlines-core
  - > Structured generation in Rust
