### ISSUE TITLE
node + npm minimum requirements missing from README

### ISSUE THREAD

**Issue by ktorn** [jehna/humanify#24]
The Ubuntu 24.04 LTS APT repository only ships with node v18 and npm v9 which will not work for this project.

Please specify the minimum requirements in the README.

**Comment by jehna** [comment]
Thank you for pointing it out! Added a note about the requirement to README.

You can install more recent node.js via `apt install` if you add the nodesource to your apt sources and keyring, check:
https://github.com/nodesource/distributions?tab=readme-ov-file#using-ubuntu-nodejs-22
