### ISSUE TITLE
bugs: Device memory allocation of size 1610612736 failed.

### ISSUE THREAD

**Issue by NguyenDuck** [jehna/humanify#258]
### Command
```shell
$ humanify local "E:\file.js"
```

### Log
```
(node:15220) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ggml_vulkan: Compiling shaders..............................Done!
ggml_vulkan: Device memory allocation of size 1610612736 failed.
ggml_vulkan: vk::Device::allocateMemory: ErrorOutOfDeviceMemory
[node-llama-cpp] llama_kv_cache_init: failed to allocate buffer for kv cache
[node-llama-cpp] llama_new_context_with_model: llama_kv_cache_init() failed for self-attention cache
file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/node-llama-cpp/dist/evaluator/LlamaContext/LlamaContext.js:551
                    throw new Error("Failed to create context");
                          ^

Error: Failed to create context
    at createContext (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/node-llama-cpp/dist/evaluator/LlamaContext/LlamaContext.js:551:27)
    at async LlamaContext._create (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/node-llama-cpp/dist/evaluator/LlamaContext/LlamaContext.js:597:24)
    at async Object.<anonymous> (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/node-llama-cpp/dist/evaluator/LlamaModel/LlamaModel.js:297:24)
    at async withLock (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/lifecycle-utils/dist/withLock.js:36:16)
    at async LlamaModel.createContext (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/node-llama-cpp/dist/evaluator/LlamaModel/LlamaModel.js:294:16)
    at async llama (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/humanifyjs/dist/index.mjs:127:19)
    at async Command.<anonymous> (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/humanifyjs/dist/index.mjs:55190:18)

Node.js v22.11.0
```

### Hardware Infomation
 - OS: Windows 11
 - GPU: Geforce GTX 1050 TI ( 12 GB )
 - Ram: 16 GB

**Comment by jehna** [comment]
Seems that humanify is trying to use more memory than what's available at your system.

You can try tweaking the `--contextSize` value to a lower one (worse results but should use less memory). Try e.g. `--contextSize 200`

**Comment by NguyenDuck** [comment]
> Seems that humanify is trying to use more memory than what's available at your system.
> 
> You can try tweaking the `--contextSize` value to a lower one (worse results but should use less memory). Try e.g. `--contextSize 200`

Already tried but it isnt resolved!

**Comment by jehna** [comment]
I'm afraid that Humanify needs a bit more memory from your gpu then. The smaller model is based on phi 3.1 mini q4 k m, which in theory should fit a 12gb VRAM, but I'm not sure I have the time right now to debug the issue.

You could check if you can run the same model with llama.cpp on your local machine. This way we could check if there's something that Humanify could do differently (it's using llama.cpp bindings behind the scenes).

**Comment by NguyenDuck** [comment]
@jehna the contextSize didnt sent to https://github.com/jehna/humanify/blob/6db3dbb4d12afb5d67aff5e7331f0976110e745d/src/plugins/local-llm-rename/llama.ts#L19-L23
called from
https://github.com/jehna/humanify/blob/6db3dbb4d12afb5d67aff5e7331f0976110e745d/src/commands/local.ts#L38-L42

**Comment by jehna** [comment]
> The contextSize didnt sent to

Yep, it's not a feature of LLAMA, but it means the amount of code that's sent to the LLM as a context to do the renaming. It's sent to the function `localReanme`:

https://github.com/jehna/humanify/blob/6db3dbb4d12afb5d67aff5e7331f0976110e745d/src/commands/local.ts#L43-L47

This gets passed all the way to `scopeToString`, which uses some simple heuristics to determine which part of example code to include:

https://github.com/jehna/humanify/blob/6db3dbb4d12afb5d67aff5e7331f0976110e745d/src/plugins/local-llm-rename/visit-all-identifiers.ts#L96-L122

Using a lower `contextSize` should reduce emory usage by a small amount, as it puts less tokens to the LLM's input

**Comment by NguyenDuck** [comment]
I got it
