### ISSUE TITLE
Create official releases + changelog notes

### ISSUE THREAD

**Issue by 0xdevalias** [jehna/humanify#31]
It would be cool if you were able to make some official github releases to help track the versions + changelog + etc:

- https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

I only found out that the 2.0 version came out by accident:

> This should now be fixed in v2 since there's the long awaited JSON mode with the new [structured outputs](https://openai.com/index/introducing-structured-outputs-in-the-api/).  Please take a look and repoen if anything comes up
> 
> _Originally posted by @jehna in https://github.com/jehna/humanify/issues/22#issuecomment-2282876269_

**Comment by 0xdevalias** [comment]
Also, it looks like the v2 branch may have been started from scratch, rather than continuing on from the historical branch. Why was that?

**Comment by jehna** [comment]
> It would be cool if you were able to make some official github releases to help track the versions + changelog + etc

Yes, let's do this for new versions! I think I can generate a changelog and versioning automatically while doing a new release to npm.

> Also, it looks like the v2 branch may have been started from scratch (first commit: https://github.com/jehna/humanify/commit/e9770a63461835aac2e23fe0b0761610046cc634), rather than continuing on from the historical branch (https://github.com/jehna/humanify/tree/v1). Why was that?

Yes, v2 was a complete rewrite from scratch, so I started with an orphan branch. Probably should have rebased on top of a clean-wiped v1 to ensure `git pull` would have worked for others that had cloned the repo, I can imagine it caused quite some conflicts. Sorry about that 😬

**Comment by jehna** [comment]
I've used this in some other projects, could become handy here too:
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by jehna** [comment]
Here's the docs for `gh release create --generate-notes`:
https://cli.github.com/manual/gh_release_create

**Comment by jehna** [comment]
Should work now, creates this kind of autogenerated release notes:
https://github.com/jehna/humanify/releases/tag/v2.1.0

**Comment by 0xdevalias** [comment]
> Should work now

@jehna Looks good!

One note/question:

> I get that you might want to suppress dependabot as 'noise'; but I also wonder if knowing what libraries were updated might be useful? At least for main dependencies (devDependencies probably less so)
> 
> _Originally posted by @0xdevalias in https://github.com/jehna/humanify/pull/42#discussion_r1719339469_
