### ISSUE TITLE
chat gpt api problem

### ISSUE THREAD

**Issue by abdurrahim11** [jehna/humanify#47]
"429 Your account is not active, please check your billing details on our website." It is giving error. I have used it before but there was no problem then, now the problem is happening.

screenshot of billing: https://prnt.sc/IK_vlvagrwH8

I have tested the api with the following codes but it is working again with these codes. The problem occurs when running humanify
Responses: https://prnt.sc/11o6iOGCykVc

curl -X POST https://api.openai.com/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer sk-proj-redacted" \
-d '{
  "model": "gpt-4",
  "messages": [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Give me 10 city names."}
  ]
}'

RateLimitError: 429 Your account is not active, please check your billing details on our website.
    at APIError.generate (file:///C:/Users/asus/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/openai/error.mjs:59:20)
    at OpenAI.makeStatusError (file:///C:/Users/asus/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///C:/Users/asus/AppData/Roaming/npm/node_modules/humanifyjs/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/asus/AppData/Roaming/npm/node_modules/humanifyjs/dist/index.mjs:56726:26
    at async visitAllIdentifiers (file:///C:/Users/asus/AppData/Roaming/npm/node_modules/humanifyjs/dist/index.mjs:56598:21)
    at async file:///C:/Users/asus/AppData/Roaming/npm/node_modules/humanifyjs/dist/index.mjs:56720:12
    at async unminify (file:///C:/Users/asus/AppData/Roaming/npm/node_modules/humanifyjs/dist/index.mjs:196:27)
    at async Command.<anonymous> (file:///C:/Users/asus/AppData/Roaming/npm/node_modules/humanifyjs/dist/index.mjs:56790:3) {
  status: 429,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8b6253594dba7712-DAC',
    connection: 'keep-alive',
    'content-length': '223',
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 20 Aug 2024 12:18:22 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=redacted; path=/; expires=Tue, 20-Aug-24 12:48:22 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=pyggojEwGLj_r3_Zvn3B8Q.YuTVm_s6VUP1RNbPdGlg-1724156302573-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_21252e15fa240fc5b3f53e339af0f906'
  },

**Comment by jehna** [comment]
Hey! It seems that you just posted your secret token publicly. I removed the token's details from this PR, but I'd recommend revoking the token, as there are a lot of bots that scan Github automatically for any tokens.

**Comment by jehna** [comment]
Does the issue persist if you create a new token?

**Comment by abdurrahim11** [comment]
I have generated new api key but still having problem

**Comment by abdurrahim11** [comment]
@jehna 
chatgpt has different api tell me which api are you using for humanify.When I tested with the below code it was working but not working in humanify.

curl -X POST https://api.openai.com/v1/chat/completions
-H "Content-Type: application/json"
-H "Authorization: Bearer sk-proj-redacted"
-d '{
"model": "gpt-4",
"messages": [
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": "Give me 10 city names."}
]
}'

**Comment by jehna** [comment]
Can you try the same code with the model `gpt-4o-mini`? That's the default model used by humanify. Alternatively you can try `--model gpt-4` flag with Humanify to use the same model your example code is using

**Comment by abdurrahim11** [comment]
I tried with gpt-4o-mini but it is working
Screenshot: https://prnt.sc/WlS44qZO5UQc

gpt-4o-mini  code:
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer your-api-key" \
  -d '{
  "model": "gpt-4o-mini",
  "messages": [{"role": "user", "content": "Test message for GPT-4o-mini"}],
  "max_tokens": 50
}'

When I try with humanify I get "RateLimitError: 429 Your account is not active, please check your billing details on our website."

**Comment by 0xdevalias** [comment]
> I removed the token's details from this ~PR~

@jehna FYI, in the case of exposed secrets like this, it's not enough to just edit the post, but you need to also remove the old edit history, otherwise it's still exposed there.

- https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history

**Comment by 0xdevalias** [comment]
> I tried with gpt-4o-mini but it is working
> Screenshot: [prnt.sc/WlS44qZO5UQc](https://prnt.sc/WlS44qZO5UQc)

@abdurrahim11 It looks like you may have exposed your API token again in this screenshot, so if you haven't already, you should delete and re-generate that one as well.

**Comment by jehna** [comment]
Have you verified your email? https://community.openai.com/t/chatgpt-your-account-is-not-active/28667/2

**Comment by jehna** [comment]
Closing due inactivity, please reopen if needed
