### ISSUE TITLE
Module 'guidance' has no attribute 'llms'

### ISSUE THREAD

**Issue by cairocoder** [jehna/humanify#6]
When I run below:
`npm start -- --local -o unminified.js app.min.js`
I got an error: AttributeError: module 'guidance' has no attribute 'llms'. Did you mean: 'llm'?

Here's the full terminal output:

```
Traceback (most recent call last):
  File "/Users/cairocoder/Sites/localhost/humanify/local-inference/inference-server.py", line 3, in <module>
    from rename import rename
  File "/Users/cairocoder/Sites/localhost/humanify/local-inference/rename.py", line 2, in <module>
    from guidance_config import guidance
  File "/Users/cairocoder/Sites/localhost/humanify/local-inference/guidance_config.py", line 4, in <module>
    guidance.llm = guidance.llms.Transformers(mname, device="mps", caching=False, temperature=0.5)
                   ^^^^^^^^^^^^^
AttributeError: module 'guidance' has no attribute 'llms'. Did you mean: 'llm'?
```

**Comment by aaronegger** [comment]
I have the same issue

**Comment by aaronegger** [comment]
Try changing it to this:

import guidance
from guidance import models

mname = "meta-llama/Llama-2-7b-chat-hf"
guidance.llm = models.Transformers(mname, device="mps", caching=False, temperature=0.5)

**Comment by jehna** [comment]
Fixed at v2, no Python needed anymore

**Comment by AGenchev** [comment]
which version of guidance you have ? I guess it has developed and changed its API.

**Comment by jehna** [comment]
I actually dropped guidance (and python) in v2, I'm now using [gbnf grammars](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md) to force a specific output instead of using Guidance.

**Comment by 0xdevalias** [comment]
Interesting anecdote, llama.cpp has support for the rust-based version of guidance built in now, and is also what is used by the OpenAI API for their JSON Schemas now too:

- https://github.com/guidance-ai/llguidance
  - > Low-level Guidance (llguidance)
  - > 2025-05-20 LLGuidance [shipped](https://x.com/OpenAIDevs/status/1924915341052019166) in [OpenAI](https://x.com/OpenAIDevs/status/1924915343677653014) for JSON Schema
  - > 2025-02-01 integration [merged](https://github.com/ggml-org/llama.cpp/pull/10224) into llama.cpp (b4613)
    - https://github.com/ggml-org/llama.cpp/pull/10224
    - https://github.com/ggml-org/llama.cpp/blob/master/docs/llguidance.md
      - > LLGuidance supports JSON Schemas and arbitrary context-free grammars (CFGs) written in a [variant](https://github.com/guidance-ai/llguidance/blob/main/docs/syntax.md) of Lark syntax. It is [very fast](https://github.com/guidance-ai/jsonschemabench/tree/main/maskbench) and has [excellent](https://github.com/guidance-ai/llguidance/blob/main/docs/json_schema.md) JSON Schema coverage but requires the Rust compiler, which complicates the llama.cpp build process.
      - > There are no new command-line arguments or modifications to `common_params`. When enabled, grammars starting with `%llguidance` are passed to LLGuidance instead of the [current](https://github.com/ggml-org/llama.cpp/blob/master/grammars/README.md) llama.cpp grammars. Additionally, JSON Schema requests (e.g., using the `-j` argument in `llama-cli`) are also passed to LLGuidance.
      - > For your existing GBNF grammars, you can use [gbnf_to_lark.py script](https://github.com/guidance-ai/llguidance/blob/main/python/llguidance/gbnf_to_lark.py) to convert them to LLGuidance Lark-like format.
        - https://github.com/guidance-ai/llguidance/blob/main/docs/syntax.md
          - > LLGuidance supports a variant of syntax used by Python [Lark parsing toolkit](https://github.com/lark-parser/lark). We also provide a [gbnf_to_lark.py script](https://github.com/guidance-ai/llguidance/blob/main/python/llguidance/gbnf_to_lark.py) to convert from [GBNF](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md) format used in [llama.cpp](https://github.com/ggerganov/llama.cpp). These makes it easier to get started with a new grammar, and provide a familiar syntax, however neither is a drop-in replacement for Lark or GBNF.
